//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardGame_Model.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SachinKanzariya_452Entities : DbContext
    {
        public SachinKanzariya_452Entities()
            : base("name=SachinKanzariya_452Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserTable> UserTable { get; set; }
        public virtual DbSet<Wallet> Wallet { get; set; }
        public virtual DbSet<TransactionsHistory> TransactionsHistory { get; set; }
    }
}
