//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardGame_Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsHistory
    {
        public int Transaction_id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> DebitAmount { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> ChanceLeft { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
