//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardGame_Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int WalletID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TotalBalance { get; set; }
        public Nullable<byte> RemainingChance { get; set; }
        public Nullable<System.DateTime> transactiondate { get; set; }
        public Nullable<int> CreditedAmount { get; set; }
        public Nullable<int> DebitedAmount { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
